### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by holmars** [holmars/leider#2]
### Default env var name

The following is the contents of `leider.yaml`.
 
```yaml
db:
  image: postgres:9.6-alpine
```

Should the default env var be
- `POSTGRESQL_URL`, or
- `DB_URL`.

### Configurable

The following is the contents of `leider.yaml`.

```yaml
db:
  image: postgres:9.6-alpine
  env_var: DATABASE_URL
```
